server:
  port: 8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
    urls:
      - name: User Management v1
        url: /openapi/user-management.yaml


spring:
  application:
    name: "crediya-ms-user-management"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"




jwt:
  json-exp-roles: "/roles"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,mappings"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8082"

routes:
  paths:
    users: "/api/v1/users"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "authentication"
    schema: "public"
    username: "postgres"
    password: "postgres"
